### PR TITLE
Requests: Add GetSourceDefaultSettings

### LINKED ISSUE #432: Add request type to get the settings specification for a specified source type
##### Issue type
GetSourceFilterInfo and GetSourceFilters return an empty "settings" property when default values are set.

##### Description
When requesting filters via GetSourceFilterInfo and GetSourceFilters, the response data has an empty object for the "settings" property UNLESS the fields are set to something other than their default value OR they are manually set to their default value (via text fields, dropdowns, sliders, etc).  "Default Settings" buttons will result in the values not being reported via the websocket interface.

##### Steps to reproduce and other useful info
Create a new filter on a source, but do not change from the default values.  Call GetSourceFilterInfo or GetSourceFilters.  The "settings" property is an empty object.

Changing a single setting in the Filters options and rerunning the same request code results in that single setting appearing in the setting object.

Changing the setting back to the original setting (manually, NOT via defaults button) properly sends the setting.

Clicking the Defaults button resets everything, resulting in the empty settings object again.

- The Color Correction filter, for example, has a default GAMMA value of 0 (zero).
- Requesting settings for that filter results in {}
- Manually change Gamma to 1
- Requesting settings again results in { gamma : 1 }
- Manually change Gamma back to 0
- Requesting settings results in { gamma : 0 }
- Press Defaults button to reset settings
- Requesting settings results in {}

NOTE: Settings visibility DOES persist after closing and relaunching OBS.  If the settings appear in one request, they will continue to appear after closing and relaunch.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 24.0.3
- **OBS WebSocket version** : 4.7.0
- **OBS WebSocketJS version** : 4.0.1

### PR DESCRIPTION
**Pull request by tt2468**
### Description

Adds a request, mainly for development purposes, which returns an object of default settings for a given sourceKind (eg. `vlc_source`)

### Motivation and Context

Fixes #432 
Users have long been told to customize each value of a given source, then use `GetSourceSettings` to get the values, as OBS' `obs_data_get_json()` function only returns non-default values. This simplifies the process by allowing developers to directly request the default keys and values for a given source kind.

### How Has This Been Tested?

Tested OS(s): Ubuntu 20.04

### Types of changes

- New request/event (non-breaking)
- Documentation change (a change to documentation pages)

### Checklist:

-   [x] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [x] My code is not on the master branch.
-   [x] The code has been tested.
-   [x] All commit messages are properly formatted and commits squashed where appropriate.
-   [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: src/WSRequestHandler_Sources.cpp [hunk 1]
```diff
@@ -1679,6 +1679,40 @@ RpcResponse WSRequestHandler::SetAudioMonitorType(const RpcRequest& request)
 	return request.success();
 }
 
+/**
+* Get the default settings for a given source type.
+*
+* @param {String} `sourceKind` Source name.
+*
```
Comment (Palakis) [inline src/WSRequestHandler_Sources.cpp:1686]: Missing a `@return` line for `defaultSettings`

File: src/WSRequestHandler_Sources.cpp [hunk 2]
```diff
@@ -1679,6 +1679,40 @@ RpcResponse WSRequestHandler::SetAudioMonitorType(const RpcRequest& request)
...
+
+    OBSDataAutoRelease defaultData = obs_get_source_defaults(sourceKind.toUtf8());
+    if (!defaultData) {
+        return request.failed("invalid sourceKind");
+    }
+
+    OBSDataAutoRelease defaultSettings = Utils::OBSDataGetDefaults(defaultData);
+
+    OBSDataAutoRelease response = obs_data_create();
+    obs_data_set_obj(response, "defaultSettings", defaultSettings);
```
Comment (Palakis) [inline src/WSRequestHandler_Sources.cpp:1712]: Might be a good idea to put a reminder of sourceKind in the response.

File: src/WSRequestHandler_Sources.cpp [hunk 3]
```diff
@@ -1679,6 +1679,40 @@ RpcResponse WSRequestHandler::SetAudioMonitorType(const RpcRequest& request)
...
+* @since 4.9.0
+*/
+RpcResponse WSRequestHandler::GetSourceDefaultSettings(const RpcRequest& request)
+{
+	if (!request.hasField("sourceKind")) {
+		return request.failed("missing request parameters");
+	}
+
+    QString sourceKind = obs_data_get_string(request.parameters(), "sourceKind");
+
```
Comment (Palakis) [inline src/WSRequestHandler_Sources.cpp:1699]: nitpick: remove this blank line to group the `if` statement with the variable it checks

File: src/WSRequestHandler.cpp [hunk 4]
```diff
@@ -118,6 +118,7 @@ const QHash<QString, RpcMethodHandler> WSRequestHandler::messageMap{
 	{ "SetSourceSettings", &WSRequestHandler::SetSourceSettings },
 	{ "GetAudioMonitorType", &WSRequestHandler::GetAudioMonitorType },
 	{ "SetAudioMonitorType", &WSRequestHandler::SetAudioMonitorType },
+    { "GetSourceDefaultSettings", &WSRequestHandler::GetSourceDefaultSettings },
```
Comment (Palakis) [inline src/WSRequestHandler.cpp:121]: Wrong indent type: we use tabs in C/C++ code.

File: src/WSRequestHandler_Sources.cpp [hunk 5]
```diff
@@ -1679,6 +1679,40 @@ RpcResponse WSRequestHandler::SetAudioMonitorType(const RpcRequest& request)
...
+* @category sources
+* @since 4.9.0
+*/
+RpcResponse WSRequestHandler::GetSourceDefaultSettings(const RpcRequest& request)
+{
+	if (!request.hasField("sourceKind")) {
+		return request.failed("missing request parameters");
+	}
+
+    QString sourceKind = obs_data_get_string(request.parameters(), "sourceKind");
```
Comment (Palakis) [inline src/WSRequestHandler_Sources.cpp:1698]: I noticed there a several instances of mixed indents. I noticed our `.editorconfig` may have missed an `indent_size` alongside `indent_style = tab` to work properly. Can you sync with the main branch and see if your editor picks it up?

File: src/Utils.cpp [hunk 6]
```diff
@@ -905,3 +906,52 @@ void Utils::AddSourceHelper(void *_data, obs_scene_t *scene)
...
+	volatile long ref;
+	struct obs_data *parent;
+	struct obs_data_item *next;
+	enum obs_data_type type;
+	size_t name_len;
+	size_t data_len;
+	size_t data_size;
+	size_t default_len;
+	size_t default_size;
+    size_t autoselect_size;
```
Comment (Palakis) [inline src/Utils.cpp:920]: Bad indent here as well.

File: src/Utils.cpp [hunk 7]
```diff
@@ -905,3 +906,52 @@ void Utils::AddSourceHelper(void *_data, obs_scene_t *scene)
...
+    obs_data_item_t *item = NULL;
+
+    for (item = obs_data_first(data); item; obs_data_item_next(&item)) {
+        enum obs_data_type type = obs_data_item_gettype(item);
+        const char *name = (char *)item + sizeof(struct obs_data_item);
+
+        if (type == OBS_DATA_STRING) {
+			const char *val = obs_data_item_get_string(item);
+            obs_data_set_string(returnData, name, val);
+		} else if (type == OBS_DATA_NUMBER) {
```
Comment (Palakis) [inline src/Utils.cpp:936]: Indentation is all over the place in that function.

**Review by Palakis — CHANGES_REQUESTED** [review]

File: src/Utils.cpp [hunk 8]
```diff
@@ -905,3 +906,52 @@ void Utils::AddSourceHelper(void *_data, obs_scene_t *scene)
...
+};
+
+obs_data_t *Utils::OBSDataGetDefaults(obs_data_t *data)
+{
+	obs_data_t *returnData = obs_data_create();
+	obs_data_item_t *item = NULL;
+
+	for (item = obs_data_first(data); item; obs_data_item_next(&item)) {
+		enum obs_data_type type = obs_data_item_gettype(item);
+		const char *name = (char *)item + sizeof(struct obs_data_item);
```
Comment (Palakis) [inline src/Utils.cpp:931]: Isn't using `obs_data_item_get_name(obs_data_item_t*)` simpler than pulling off this hack?

**Review by Palakis — APPROVED** [review]

**Review by Palakis — APPROVED** [review]
